### PR TITLE
Tests/add rspec

### PR DESCRIPTION
**Pull request by TylerRockwell**
### Why?
As Whitewidow grows, the code will become harder to maintain and harder to manually test to ensure no new bugs have been introduced.

By adding tests, separating the code into classes with a single responsibility, and reducing coupling between said classes, changes will be easier and safer to make.

### What Changed?
* Extracted `Scanner` logic out to a separate module. `lib/whitewidow/scanner.rb`
  - This includes all methods not related to the OptionParser or the main case statement that was in `whitewidow.rb`
  - These changes are a preliminary attempt to move towards OOP best practices

* Introduced RSpec testing framework
  - Wrote tests for new `Scanner` module that tests a good portion of the primary logic

* Added Webmock and VCR to ensure tests are not doing _live_ scans

### CODE REVIEW

**Comment by Ekultek** [comment]
This is a lot of stuff changed, you're going to need to give me a few days to test it

**Review by Ekultek — COMMENTED** [review]
Testing

**Comment by TylerRockwell** [comment]
No worries. There was a bit that needed to be added/changed to get it into a good testable state. Most of the non-testing code is the same as before, just moved into a new class (though some methods now take parameters instead of reading `OPTIONS` directly).

On the bright side, once you review the tests, just running `rspec` should help to give confidence that things aren't completely broken in the future.

**Review by Ekultek — DISMISSED** [review]
`File.truncate('tmp/#sites.txt', 0)` from `rspec/spec_helper` needs to be non hardcoded, you can use the `FILE_FLAG_FILE_PATH` constant instead of hardcoding the file name. From `lib/whitewidow/scanner.rb` line 25,  `spec/spec_helper.rb` line 19, and `expect(IO.read("#{PATH}/tmp/#sites.txt")).to eq("#{test_website}\n")` in `spec/whitewidow/scanner_spec.rb` line 28.

**Comment by Ekultek** [comment]
This was reverted, the `rspec` fails with this:

```
$ rspec
FF.......

Failures:

  1) Whitewidow::Scanner usage_page displays usage info
     Failure/Error: File.truncate('tmp/#sites.txt', 0)

     Errno::ENOENT:
       No such file or directory @ rb_file_s_truncate - tmp/#sites.txt
     # ./spec/spec_helper.rb:19:in `truncate'
     # ./spec/spec_helper.rb:19:in `block (2 levels) in <top (required)>'

  2) Whitewidow::Scanner usage_page displays a reference to the README
     Failure/Error: File.truncate('tmp/#sites.txt', 0)

     Errno::ENOENT:
       No such file or directory @ rb_file_s_truncate - tmp/#sites.txt
     # ./spec/spec_helper.rb:19:in `truncate'
     # ./spec/spec_helper.rb:19:in `block (2 levels) in <top (required)>'

Finished in 4.62 seconds (files took 10.19 seconds to load)
9 examples, 2 failures

Failed examples:

rspec ./spec/whitewidow/scanner_spec.rb:6 # Whitewidow::Scanner usage_page displays usage info
rspec ./spec/whitewidow/scanner_spec.rb:10 # Whitewidow::Scanner usage_page displays a reference to the README

```

Fix it and i'll merge it

**Comment by Ekultek** [comment]
I fixed it, remerging

**Pull request merged**
