### PR TITLE
sqlmap update didn't work.

### PR DESCRIPTION
**Pull request by jantoniorobledo**
I have change the line 157 to move to the right path where sqlmap is installed. Also the way to do the upate is using git pull.

### CODE REVIEW

**Comment by Ekultek** [comment]
Why use git pull in place of sqlmaps update? They do the same thing and one looks fancier

**Comment by jantoniorobledo** [comment]
Trying to do the update on on your way, I'm getting this error:
[12:45:05] [ERROR] not a git repository. Please checkout the 'sqlmapproject/sqlmap' repository from GitHub (e.g. 'git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap')
[12:45:05] [INFO] for Linux platform it's required to install a standard 'git' package (e.g.: 'sudo apt-get install git')

This is the reason

**Comment by Ekultek** [comment]
Running `git pull` in the repo will only update the repo itself. So when you `git pull` in whitewidow, only whitewidow is updated. This is because whitewidow is the main program, and sqlmap is a thirdparty, so git resolves the to the main .git files

**Comment by Ekultek** [comment]
Lemme send a push and have you update from that push

**Comment by Ekultek** [comment]
This will not be implemented. Closing.

**Review by Ekultek — COMMENTED** [review]
No.

**Pull request closed without merging**
