### PR TITLE
Refactor/scanner

### PR DESCRIPTION
**Pull request by TylerRockwell**
### Why?
Large methods are hard to read/follow/debug/change

### What Changed?
* Simplified some methods in `settings.rb`
* Refactored `format_file` in `scanner.rb`
* Removed `Copy` module in favor of Ruby's [`FileUtil.copy`](http://ruby-doc.org/stdlib-2.2.2/libdoc/fileutils/rdoc/FileUtils.html#method-c-cp) method
* Added `pry-byebug` for easier step-by-step debugging

### CODE REVIEW

**Comment by Ekultek** [comment]
What is the purpose of adding pry to this?

**Comment by TylerRockwell** [comment]
Pry is there for ease of debugging. We don't have to keep it in the Gemfile if you don't want, but I thought it may be easier than adding it whenever we need to step through the code.

**Comment by Ekultek** [comment]
Okay, just thought you might have some auto debugging tactic that I didn't know about, will this still remove blank lines from files and all white space? For example:

Turn this:
```
http://example.example.com/php?id=is

        http://example.example.com/php?id=i


  http://example.example.com/php?id=it
```

Into this:
```
http://example.example.com/php?id=is
http://example.example.com/php?id=i
http://example.example.com/php?id=it
```

**Comment by TylerRockwell** [comment]
Hmm...looks like it's not at the moment. Hold off on merging this, and I'll figure out what's going on.

Blank lines are still getting removed, but leading whitespace is still there.

**Comment by Ekultek** [comment]
Take your time man

**Comment by TylerRockwell** [comment]
It's fixed. I was just missing `.strip` in this block
```
{ |outfile| outfile.puts(line.strip) unless line.chomp.empty? }
```

**Comment by TylerRockwell** [comment]
I'll add a test for that in the near future.

**Comment by Ekultek** [comment]
Drop pry and I'll test it tomorrow morning

**Comment by Ekultek** [comment]
You know what actually I have an idea for pry so keep it there and I'll test it tomorrow

**Comment by Ekultek** [comment]
It won't find the files

```
 __      __.__    .__  __         __      __.__    .___
/  \    /  \  |__ |__|/  |_  ____/  \    /  \__| __| _/______  _  __
\   \/\/   /  |  \|  \   __\/ __ \   \/\/   /  |/ __ |/  _ \ \/ \/ /
 \        /|   Y  \  ||  | \  ___/\        /|  / /_/ (  <_> )     /
  \__/\  / |___|  /__||__|  \___  >\__/\  / |______ | \____/ \/\_/
       \/       \/              \/      \/           \/    v1.9.5.8(dev)

Clone: https://github.com/WhitewidowScanner/whitewidow.git
Downloads: https://github.com/WhitewidowScanner/whitewidow/releases
[ ! ] Use of this program for malicious intent is illegal. For more information
run the --legal flag

[08:37:37 INFO] Formatting file

Hey now my friend, I know you're eager, I am also, but that file tmp/sites.txt
either doesn't exist, or it's not in the directory you say it's in..

I'm gonna need you to go find that file, move it to the correct directory and th
en
run me again.

Don't worry I'll wait!
```

**Comment by Ekultek** [comment]
hahahaha nvm...

**Comment by Ekultek** [comment]
alright so drop pry from the gem file and i'll merge it

**Review by Ekultek — APPROVED** [review]
accepted

**Pull request merged**
